import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 'types' comentado porque no se usa actualmente
interface LayoutProps {
  children: React.ReactNode;
  types?: string; // 'types' es opcional
}

export default function RootLayout({ children, types }: LayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-types={types} // se puede usar 'types' aquí
      >
        {children}
      </body>
    </html>
  );
}
